# Generated by Django 5.1.3 on 2025-03-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artist_genre_album_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
