# Generated by Django 5.1.3 on 2025-03-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_music_is_trending_music_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
    ]
